name: Node CI

on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      container: ubuntu:18.04
      steps:
          - uses: actions/checkout@v4.1.1
          - uses: actions/setup-node@v4
            with:
              node-version: 14
          - run: npm install -g yarn
          - run: yarn install
          - run: yarn test
