name: Node CI

on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      container: ubuntu:18.04
      strategy:
          matrix:
            node-version: [14.x, 16.x]
      steps:
          - uses: actions/checkout@v4.1.1
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}
          - run: yarn install
          - run: yarn test
