name: Node CI

on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      container: node:18
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Set up Node.js 18
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: yarn install

        - name: Install necessary dependencies for Chromium
          run: |
            wget https://launchpad.net/ubuntu/+archive/primary/+files/libnss3_3.53.1-1ubuntu0.4_amd64.deb
            dpkg -x libnss3_3.53.1-1ubuntu0.4_amd64.deb $HOME/libnss3
            export LD_LIBRARY_PATH=$HOME/libnss3/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH


        - name: Setup Chrome
          uses: browser-actions/setup-chrome@v1

        - name: Run tests
          run: yarn test
