name: Node CI

on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      container: node:18
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Set up Node.js 18
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - run: npm install chromedriver
        - name: Setup Chrome
          uses: browser-actions/setup-chrome@v1
        - run: chrome --version
        - run: yarn install
        - run: yarn test
